export default [
    {
        imageUrl:'/cover2.png'
    },
    {
        imageUrl:'/cover3.png'
    },
    {
        imageUrl:'/cover4.png'
    },
    {
        imageUrl:'/cover5.png'
    },
    {
        imageUrl:'/cover6.png'
    },
    {
        imageUrl:'/cover7.png'
    },
    {
        imageUrl:'/cover8.png'
    },
    {
        imageUrl:'/cover9.png'
    },
    {
        imageUrl:'/cover10.png'
    },
    {
        imageUrl:'/cover11.png'
    },
    {
        imageUrl:'/cover12.png'
    },
    {
        imageUrl:'/cover13.png'
    },
]